const allCountries = [
  "Albania",
  "Argentina",
  "Armenia",
  "Australia",
  "Azerbaijan",
  "Belarus",
  "Bolivia",
  "Botswana",
  "Bulgaria",
  "Brazil",
  "Cambodia",
  "Canada",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Egypt",
  "El Salvador",
  "Euro Countries",
  "Fiji",
  "Ghana",
  "Guatemala",
  "Guinea",
  "Guyana",
  "Hong Kong",
  "Honduras",
  "Hungary",
  "Indonesia",
  "India",
  "Iceland",
  "Iran",
  "Israel",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Malawi",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Namibia",
  "Nepal",
  "New Zealand",
  "Norway",
  "Oman",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Seychelles",
  "Singapore",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Thailand",
  "Trinidad and Tobago",
  "Turkey",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zimbabwe",
];
export const countries = [
  "Germany",
  "Norway",
  "Poland",
  "Romania",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Brazil",
  "Canada",
  "China",
  "Albania",
  "Australia",
  "Azerbaijan",
  "Belarus",
  "Bulgaria",
  "Hungary",
  "India",
  "Iceland",
  "Israel",
  "Japan",
  "Croatia",
  "Denmark",
  "Egypt",
  "Mexico",
  "New Zealand",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "South Africa",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Vietnam",
];

export const testRates = {
  EUR: 1,
  NOK: 9.963647,
  PLN: 4.595917,
  RON: 4.9541,
  UAH: 30.795203,
  GBP: 0.853223,
  USD: 1.15975,
  BRL: 6.326668,
  CAD: 1.463443,
  CNY: 7.47656,
  ALL: 121.43293,
  AUD: 1.596122,
  AZN: 1.971837,
  BGN: 1.955299,
  HUF: 356.159413,
  INR: 86.415902,
  ISK: 148.819086,
  ILS: 3.742886,
  JPY: 128.934108,
  HRK: 7.494767,
  DKK: 7.438057,
  EGP: 18.207968,
  MXN: 23.826256,
  NZD: 1.670464,
  RUB: 84.190226,
  SAR: 4.349426,
  RSD: 117.436757,
  SGD: 1.575121,
  ZAR: 17.481625,
  SEK: 10.147355,
};
